### ISSUE TITLE
torchvision-nightly installation fails

### ISSUE THREAD

**Issue by 009deep** [Paperspace/fastai-docker-deprecated#10]
RUN /opt/conda/bin/conda install -c conda-forge --name fastai -c fastai torchvision-nightly fails with error

PackagesNotFoundError: The following packages are not available from current channels:

  - torchvision-nightly

**Comment by ldelossa** [comment]
@009deep 

We just reworked how the fastai-v3 container is built. Sorry for the delay but can you return and confirm it now works.

**Comment by ldelossa** [comment]
@009deep 

Please note we have recently deprecated this repository and have moved to: https://github.com/Paperspace/fastai-docker

Please follow this new repo for updates on our fastai course containers.
