### ISSUE TITLE
Whats' the password to access notebook?

### ISSUE THREAD

**Issue by SharatSingh** [Paperspace/fastai-docker-deprecated#3]

**Comment by dte** [comment]
It should just use the Jupyter token that is generated i.e. in the format: `http://localhost:8888/?token=c8de56fa4deed24899803e93c227592aef6538f93025fe01`

How are you running the container? Where are you getting prompted for a password?

**Comment by enod** [comment]
@SharatSingh after running the image, look at the logs that's being generated by container.

For running containers - `docker ps` 

for seeing logs from specific container - `docker logs CONTAINER_ID_HERE`

from there you can see the token.

**Comment by ldelossa** [comment]
@SharatSingh going to close this issue I'm assuming you have this issue fixed. If not feel free to open another.
