### ISSUE TITLE
fyi: this repository is over 800mb in size

### ISSUE THREAD

**Issue by AdrianLoer** [Paperspace/fastai-docker-deprecated#7]
the .git/objects/pack folder is 812 mb after checkout. Not a big deal for cloud deployments but nonetheless a bit too much for essentially three text files

**Comment by SeanPedersen** [comment]
What is the reason for this?

**Comment by dennisobrien** [comment]
Looks like the first commit included training data.  For example:
https://github.com/Paperspace/fastai-docker/tree/a1e93607ddadaf114c7ba018c6a4c7a34de2ed41/dogscats/train/dogs

There are a few folders with more than 10k image files, each about 30kb.  It's possible to fix this by re-writing git history.

Here's the output from [git-sizer](https://github.com/github/git-sizer/)

```
(base) ✔ ~/workspace/paperspace/fastai-docker [master|✔]
15:43 $ git-sizer
Processing blobs: 37421
Processing trees: 41
Processing commits: 37
Matching commits to trees: 37
Processing annotated tags: 0
Processing references: 4
| Name                         | Value     | Level of concern               |
| ---------------------------- | --------- | ------------------------------ |
| Biggest objects              |           |                                |
| * Trees                      |           |                                |
|   * Maximum entries      [1] |  12.5 k   | ************                   |

[1]  756a0b6b967693ad99aa667ece385c0ddc06d1d0 (52e6177c67255871db8efc50991a434a980e7729:dogscats/test1)
```

**Comment by ldelossa** [comment]
@AdrianLoer @SeanPedersen @dennisobrien 

Please note we have recently deprecated this repository and have moved to: https://github.com/Paperspace/fastai-docker

Please follow this new repo for updates on our fastai course containers.
