### ISSUE TITLE
Error response from daemon: manifest for paperspace/fastai:latest not found

### ISSUE THREAD

**Issue by austinmw** [Paperspace/fastai-docker-deprecated#8]
Above error from `docker pull paperspace/fastai`

Building the Dockerfile also fails with: `E: Packages were downgraded and -y was used without --allow-downgrades.`

**Comment by gaurav-gogia** [comment]
+1

**Comment by ldelossa** [comment]
@austinmw 

We just reworked how the fastai-v3 container is built. Can you please try once again.

**Comment by ldelossa** [comment]
Please note we have recently deprecated this repository and have moved to: https://github.com/Paperspace/fastai-docker

Please follow this new repo for updates on our fastai course containers.

If the issue continues to exist please file a new bug report at this new repo.

**Comment by jp776** [comment]
This is, what I get here:
docker pull paperspace/fastai
Using default tag: latest
Error response from daemon: manifest for paperspace/fastai:latest not found: manifest unknown: manifest unknown
